#!/bin/bash 
# Escalate priveleges
if [ $(id -un) != 'root' ]; then
    exec sudo $0 $*
fi

# Name of network namespace
NETNS=$(basename $0)

# Check if this namespace exists already
EXISTING=$(ip netns show | cut -d' ' -f1 | grep "^$NETNS\$")

# Find default interface
INTERFACE=$(ip route | grep default | sed 's/.*dev \(.*\)/\1/')
# Run sudo once

# Names of veth interfaces
VETH0="${NETNS}_veth0"
VETH1="${NETNS}_veth1"

# Arguments
ARGS=$*

IPTABLES=$(iptables-save)

# Find an unused subnet starting from 10.1.0.0/24 to 10.1.255.0/24
NNUM=0
while [ $NNUM -le 255 ]; do
    COUNT=$(echo "$IPTABLES" | grep -c "10\.1\.$NNUM\.0/24")

    if [ $COUNT == 0 ]; then
        break
    fi

    NNUM=$(($NNUM + 1))
done


if [ "$EXISTING" == "" ]; then
    # Create network namespace
    ip netns add $NETNS
    ip netns exec $NETNS ip link set dev lo up

    # Create veth pair
    ip link delete $VETH0 2> /dev/null
    ip link add $VETH0 type veth peer name $VETH1
    ip link set $VETH1 netns $NETNS

    # Setup the pair
    ip netns exec $NETNS ip addr add 10.1.$NNUM.1/24 dev $VETH1
    ip addr add 10.1.$NNUM.2/24 dev $VETH0
    ip netns exec $NETNS ip link set $VETH1 up
    ip link set $VETH0 up

    # Add default route inside NS
    ip netns exec $NETNS ip route add default via 10.1.$NNUM.2 dev $VETH1

    # Enable routing
    echo 1 | tee /proc/sys/net/ipv4/ip_forward > /dev/null

    # Create iptables rule if it doesn't exist already
    iptables -t nat -C POSTROUTING -s 10.1.$NNUM.0/24 -o $INTERFACE\
        -m comment --comment "for $NETNS" -j MASQUERADE 2> /dev/null

    if [ $? != 0 ]; then
        iptables -t nat -A POSTROUTING -s 10.1.$NNUM.0/24 -o $INTERFACE\
            -m comment --comment "for $NETNS" -j MASQUERADE 2> /dev/null
    fi
fi

# Use to enter the namespace and again to drop priveleges
ip netns exec $NETNS sudo -Eu $USER $ARGS

# Find all pids using this NS
PIDS=$(find -L /proc/[1-9]*/task/*/ns/net -samefile /run/netns/"$NETNS" 2> /dev/null)

if [ "$PIDS" == "" ]; then
    # Remove NS and drop iptables rule
    ip netns del $NETNS
    iptables -t nat -D POSTROUTING -s 10.1.$NNUM.0/24 -o $INTERFACE\
        -m comment --comment "for $NETNS" -j MASQUERADE 2> /dev/null
fi
